//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dear_Diary.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSData", Namespace="WS")]
    [System.SerializableAttribute()]
    public partial class SMSData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateReceivedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Originator {
            get {
                return this.OriginatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginatorField, value) != true)) {
                    this.OriginatorField = value;
                    this.RaisePropertyChanged("Originator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DateReceived {
            get {
                return this.DateReceivedField;
            }
            set {
                if ((object.ReferenceEquals(this.DateReceivedField, value) != true)) {
                    this.DateReceivedField = value;
                    this.RaisePropertyChanged("DateReceived");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WS", ConfigurationName="ServiceReference1.SMSSoap")]
    public interface SMSSoap {
        
        // CODEGEN: Generating message contract since element name SMSAccount from namespace WS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WS/sendMessage", ReplyAction="*")]
        Dear_Diary.ServiceReference1.sendMessageResponse sendMessage(Dear_Diary.ServiceReference1.sendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WS/sendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.sendMessageResponse> sendMessageAsync(Dear_Diary.ServiceReference1.sendMessageRequest request);
        
        // CODEGEN: Generating message contract since element name SMSAccount from namespace WS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WS/receiveMessage", ReplyAction="*")]
        Dear_Diary.ServiceReference1.receiveMessageResponse receiveMessage(Dear_Diary.ServiceReference1.receiveMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WS/receiveMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.receiveMessageResponse> receiveMessageAsync(Dear_Diary.ServiceReference1.receiveMessageRequest request);
        
        // CODEGEN: Generating message contract since element name SMSAccount from namespace WS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="WS/setMessagesStatusToUnread", ReplyAction="*")]
        Dear_Diary.ServiceReference1.setMessagesStatusToUnreadResponse setMessagesStatusToUnread(Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WS/setMessagesStatusToUnread", ReplyAction="*")]
        System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.setMessagesStatusToUnreadResponse> setMessagesStatusToUnreadAsync(Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessage", Namespace="WS", Order=0)]
        public Dear_Diary.ServiceReference1.sendMessageRequestBody Body;
        
        public sendMessageRequest() {
        }
        
        public sendMessageRequest(Dear_Diary.ServiceReference1.sendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WS")]
    public partial class sendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMSAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message;
        
        public sendMessageRequestBody() {
        }
        
        public sendMessageRequestBody(string SMSAccount, string Pwd, string Mobile, string Message) {
            this.SMSAccount = SMSAccount;
            this.Pwd = Pwd;
            this.Mobile = Mobile;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessageResponse", Namespace="WS", Order=0)]
        public Dear_Diary.ServiceReference1.sendMessageResponseBody Body;
        
        public sendMessageResponse() {
        }
        
        public sendMessageResponse(Dear_Diary.ServiceReference1.sendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WS")]
    public partial class sendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendMessageResult;
        
        public sendMessageResponseBody() {
        }
        
        public sendMessageResponseBody(string sendMessageResult) {
            this.sendMessageResult = sendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveMessage", Namespace="WS", Order=0)]
        public Dear_Diary.ServiceReference1.receiveMessageRequestBody Body;
        
        public receiveMessageRequest() {
        }
        
        public receiveMessageRequest(Dear_Diary.ServiceReference1.receiveMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WS")]
    public partial class receiveMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMSAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SMSPassword;
        
        public receiveMessageRequestBody() {
        }
        
        public receiveMessageRequestBody(string SMSAccount, string SMSPassword) {
            this.SMSAccount = SMSAccount;
            this.SMSPassword = SMSPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveMessageResponse", Namespace="WS", Order=0)]
        public Dear_Diary.ServiceReference1.receiveMessageResponseBody Body;
        
        public receiveMessageResponse() {
        }
        
        public receiveMessageResponse(Dear_Diary.ServiceReference1.receiveMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WS")]
    public partial class receiveMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Dear_Diary.ServiceReference1.SMSData[] receiveMessageResult;
        
        public receiveMessageResponseBody() {
        }
        
        public receiveMessageResponseBody(Dear_Diary.ServiceReference1.SMSData[] receiveMessageResult) {
            this.receiveMessageResult = receiveMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setMessagesStatusToUnreadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMessagesStatusToUnread", Namespace="WS", Order=0)]
        public Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequestBody Body;
        
        public setMessagesStatusToUnreadRequest() {
        }
        
        public setMessagesStatusToUnreadRequest(Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WS")]
    public partial class setMessagesStatusToUnreadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMSAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SMSPassword;
        
        public setMessagesStatusToUnreadRequestBody() {
        }
        
        public setMessagesStatusToUnreadRequestBody(string SMSAccount, string SMSPassword) {
            this.SMSAccount = SMSAccount;
            this.SMSPassword = SMSPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setMessagesStatusToUnreadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMessagesStatusToUnreadResponse", Namespace="WS", Order=0)]
        public Dear_Diary.ServiceReference1.setMessagesStatusToUnreadResponseBody Body;
        
        public setMessagesStatusToUnreadResponse() {
        }
        
        public setMessagesStatusToUnreadResponse(Dear_Diary.ServiceReference1.setMessagesStatusToUnreadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WS")]
    public partial class setMessagesStatusToUnreadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setMessagesStatusToUnreadResult;
        
        public setMessagesStatusToUnreadResponseBody() {
        }
        
        public setMessagesStatusToUnreadResponseBody(string setMessagesStatusToUnreadResult) {
            this.setMessagesStatusToUnreadResult = setMessagesStatusToUnreadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSSoapChannel : Dear_Diary.ServiceReference1.SMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSSoapClient : System.ServiceModel.ClientBase<Dear_Diary.ServiceReference1.SMSSoap>, Dear_Diary.ServiceReference1.SMSSoap {
        
        public SMSSoapClient() {
        }
        
        public SMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dear_Diary.ServiceReference1.sendMessageResponse Dear_Diary.ServiceReference1.SMSSoap.sendMessage(Dear_Diary.ServiceReference1.sendMessageRequest request) {
            return base.Channel.sendMessage(request);
        }
        
        public string sendMessage(string SMSAccount, string Pwd, string Mobile, string Message) {
            Dear_Diary.ServiceReference1.sendMessageRequest inValue = new Dear_Diary.ServiceReference1.sendMessageRequest();
            inValue.Body = new Dear_Diary.ServiceReference1.sendMessageRequestBody();
            inValue.Body.SMSAccount = SMSAccount;
            inValue.Body.Pwd = Pwd;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            Dear_Diary.ServiceReference1.sendMessageResponse retVal = ((Dear_Diary.ServiceReference1.SMSSoap)(this)).sendMessage(inValue);
            return retVal.Body.sendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.sendMessageResponse> Dear_Diary.ServiceReference1.SMSSoap.sendMessageAsync(Dear_Diary.ServiceReference1.sendMessageRequest request) {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.sendMessageResponse> sendMessageAsync(string SMSAccount, string Pwd, string Mobile, string Message) {
            Dear_Diary.ServiceReference1.sendMessageRequest inValue = new Dear_Diary.ServiceReference1.sendMessageRequest();
            inValue.Body = new Dear_Diary.ServiceReference1.sendMessageRequestBody();
            inValue.Body.SMSAccount = SMSAccount;
            inValue.Body.Pwd = Pwd;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            return ((Dear_Diary.ServiceReference1.SMSSoap)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dear_Diary.ServiceReference1.receiveMessageResponse Dear_Diary.ServiceReference1.SMSSoap.receiveMessage(Dear_Diary.ServiceReference1.receiveMessageRequest request) {
            return base.Channel.receiveMessage(request);
        }
        
        public Dear_Diary.ServiceReference1.SMSData[] receiveMessage(string SMSAccount, string SMSPassword) {
            Dear_Diary.ServiceReference1.receiveMessageRequest inValue = new Dear_Diary.ServiceReference1.receiveMessageRequest();
            inValue.Body = new Dear_Diary.ServiceReference1.receiveMessageRequestBody();
            inValue.Body.SMSAccount = SMSAccount;
            inValue.Body.SMSPassword = SMSPassword;
            Dear_Diary.ServiceReference1.receiveMessageResponse retVal = ((Dear_Diary.ServiceReference1.SMSSoap)(this)).receiveMessage(inValue);
            return retVal.Body.receiveMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.receiveMessageResponse> Dear_Diary.ServiceReference1.SMSSoap.receiveMessageAsync(Dear_Diary.ServiceReference1.receiveMessageRequest request) {
            return base.Channel.receiveMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.receiveMessageResponse> receiveMessageAsync(string SMSAccount, string SMSPassword) {
            Dear_Diary.ServiceReference1.receiveMessageRequest inValue = new Dear_Diary.ServiceReference1.receiveMessageRequest();
            inValue.Body = new Dear_Diary.ServiceReference1.receiveMessageRequestBody();
            inValue.Body.SMSAccount = SMSAccount;
            inValue.Body.SMSPassword = SMSPassword;
            return ((Dear_Diary.ServiceReference1.SMSSoap)(this)).receiveMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dear_Diary.ServiceReference1.setMessagesStatusToUnreadResponse Dear_Diary.ServiceReference1.SMSSoap.setMessagesStatusToUnread(Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequest request) {
            return base.Channel.setMessagesStatusToUnread(request);
        }
        
        public string setMessagesStatusToUnread(string SMSAccount, string SMSPassword) {
            Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequest inValue = new Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequest();
            inValue.Body = new Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequestBody();
            inValue.Body.SMSAccount = SMSAccount;
            inValue.Body.SMSPassword = SMSPassword;
            Dear_Diary.ServiceReference1.setMessagesStatusToUnreadResponse retVal = ((Dear_Diary.ServiceReference1.SMSSoap)(this)).setMessagesStatusToUnread(inValue);
            return retVal.Body.setMessagesStatusToUnreadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.setMessagesStatusToUnreadResponse> Dear_Diary.ServiceReference1.SMSSoap.setMessagesStatusToUnreadAsync(Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequest request) {
            return base.Channel.setMessagesStatusToUnreadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.setMessagesStatusToUnreadResponse> setMessagesStatusToUnreadAsync(string SMSAccount, string SMSPassword) {
            Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequest inValue = new Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequest();
            inValue.Body = new Dear_Diary.ServiceReference1.setMessagesStatusToUnreadRequestBody();
            inValue.Body.SMSAccount = SMSAccount;
            inValue.Body.SMSPassword = SMSPassword;
            return ((Dear_Diary.ServiceReference1.SMSSoap)(this)).setMessagesStatusToUnreadAsync(inValue);
        }
    }
}
