//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dear_Diary.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/SMSWebService/SMSService", ConfigurationName="ServiceReference1.SMSServiceSoap")]
    public interface SMSServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSWebService/SMSService/sendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string sendMessage(string MobileNo, string Message, string SMSAccount, string SMSPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSWebService/SMSService/sendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sendMessageAsync(string MobileNo, string Message, string SMSAccount, string SMSPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSWebService/SMSService/receiveMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dear_Diary.ServiceReference1.SMS[] receiveMessage(string SMSAccount, string SMSPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSWebService/SMSService/receiveMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.SMS[]> receiveMessageAsync(string SMSAccount, string SMSPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSWebService/SMSService/setMessagesStatusToUnread", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setMessagesStatusToUnread(string SMSAccount, string SMSPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SMSWebService/SMSService/setMessagesStatusToUnread", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setMessagesStatusToUnreadAsync(string SMSAccount, string SMSPassword);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SMSWebService/SMSService")]
    public partial class SMS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private string originatorField;
        
        private string dateReceivedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dateReceived {
            get {
                return this.dateReceivedField;
            }
            set {
                this.dateReceivedField = value;
                this.RaisePropertyChanged("dateReceived");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSServiceSoapChannel : Dear_Diary.ServiceReference1.SMSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceSoapClient : System.ServiceModel.ClientBase<Dear_Diary.ServiceReference1.SMSServiceSoap>, Dear_Diary.ServiceReference1.SMSServiceSoap {
        
        public SMSServiceSoapClient() {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendMessage(string MobileNo, string Message, string SMSAccount, string SMSPassword) {
            return base.Channel.sendMessage(MobileNo, Message, SMSAccount, SMSPassword);
        }
        
        public System.Threading.Tasks.Task<string> sendMessageAsync(string MobileNo, string Message, string SMSAccount, string SMSPassword) {
            return base.Channel.sendMessageAsync(MobileNo, Message, SMSAccount, SMSPassword);
        }
        
        public Dear_Diary.ServiceReference1.SMS[] receiveMessage(string SMSAccount, string SMSPassword) {
            return base.Channel.receiveMessage(SMSAccount, SMSPassword);
        }
        
        public System.Threading.Tasks.Task<Dear_Diary.ServiceReference1.SMS[]> receiveMessageAsync(string SMSAccount, string SMSPassword) {
            return base.Channel.receiveMessageAsync(SMSAccount, SMSPassword);
        }
        
        public string setMessagesStatusToUnread(string SMSAccount, string SMSPassword) {
            return base.Channel.setMessagesStatusToUnread(SMSAccount, SMSPassword);
        }
        
        public System.Threading.Tasks.Task<string> setMessagesStatusToUnreadAsync(string SMSAccount, string SMSPassword) {
            return base.Channel.setMessagesStatusToUnreadAsync(SMSAccount, SMSPassword);
        }
    }
}
